@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --no-genHtml`

import './r_tree/leaf_node_test.dart' as r_tree_leaf_node_test;
import './r_tree/node_test.dart' as r_tree_node_test;
import './r_tree/non_leaf_node_test.dart' as r_tree_non_leaf_node_test;
import './r_tree/r_tree_test.dart' as r_tree_r_tree_test;
import 'package:test/test.dart';

void main() {
  r_tree_leaf_node_test.main();
  r_tree_node_test.main();
  r_tree_non_leaf_node_test.main();
  r_tree_r_tree_test.main();
}
